name: Deploy to Azure App Service

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, dom, filter, gd, json
        tools: composer:v2

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install PHP Dependencies
      run: composer install --optimize-autoloader --no-dev --no-interaction --prefer-dist

    - name: Generate key
      run: php artisan key:generate

    - name: Install Node Dependencies
      run: npm ci

    - name: Build Assets
      run: npm run build

    - name: Run Laravel production optimizations
      run: |
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache

    - name: Create deployment package
      run: |
        # Create a deployment directory
        mkdir -p deploy
        
        # Copy all necessary files to deployment directory
        cp -r app bootstrap config database public resources routes storage deploy/
        cp -r vendor deploy/
        cp .env artisan composer.json composer.lock index.php .htaccess deploy/
        cp .deployment deploy/
        
        # Copy configuration files for both Windows and Linux
        cp -r public/web.config deploy/public/  # For Windows/IIS
        cp nginx.conf startup.sh startup-simple.sh deploy/  # For Linux
        
        # Copy built assets
        cp -r public/build deploy/public/
        
        # Copy post-deployment script
        cp azure-deploy.sh deploy/
        
        # Set proper permissions (for Linux)
        chmod -R 755 deploy/storage deploy/bootstrap/cache
        if [ -f deploy/startup.sh ]; then chmod +x deploy/startup.sh; fi
        if [ -f deploy/azure-deploy.sh ]; then chmod +x deploy/azure-deploy.sh; fi
        
        # Create zip package
        cd deploy
        zip -r ../deployment.zip .
        cd ..

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: deployment.zip

